"""Init

Revision ID: 01997c851489
Revises: 7211e5e0678c
Create Date: 2022-09-11 16:18:37.303020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01997c851489'
down_revision = '7211e5e0678c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
